# Use root/example as user/password credentials
version: '3.1'

services:

  # Api
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      # Spring profile
      SPRING_PROFILES_ACTIVE: prod
