# Spring properties
spring:

  # Removes the white label error page
  resources:
    add-mappings: true
  mvc:
    throw-exception-if-no-handler-found: true

  # Defines the image exporter as default
  profiles:
    include: export-as-img

state-machine-app:
  output-path: output/
